"""cards uuid

Revision ID: 686380140bbf
Revises: d97602012925
Create Date: 2021-04-30 18:23:55.891076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686380140bbf'
down_revision = 'd97602012925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), server_default='afbef623-2256-4226-ad5e-02f617e57a12', nullable=True))
        batch_op.create_index(batch_op.f('ix_card_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_card_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('used_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), server_default='c3a55d7d-fd70-45fc-8da4-f81b81f1b057', nullable=True))
        batch_op.create_index(batch_op.f('ix_used_card_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_used_card_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_used_card_uuid'))
        batch_op.drop_index(batch_op.f('ix_used_card_code'))
        batch_op.drop_column('uuid')

    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_uuid'))
        batch_op.drop_index(batch_op.f('ix_card_code'))
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
