"""payment cards

Revision ID: d97602012925
Revises: 3e2e498156f0
Create Date: 2021-04-28 20:31:18.839212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d97602012925"
down_revision = "3e2e498156f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("code", sa.String(length=64), server_default="000000", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "used_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("code", sa.String(length=64), server_default="000000", nullable=False),
        sa.Column("balance_after_use", sa.Float(), server_default="0", nullable=False),
        sa.Column(
            "used_at",
            sa.DateTime(),
            server_default="2021-04-28 17:31:18.665211+00:00",
            nullable=True,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("balance", sa.Float(), server_default="0", nullable=True))
    op.add_column(
        "user",
        sa.Column("state", sa.String(length=64), server_default="deactivated", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "state")
    op.drop_column("user", "balance")
    op.drop_table("used_card")
    op.drop_table("card")
    # ### end Alembic commands ###
