"""user_uuid

Revision ID: e3ef8552e5d5
Revises: 686380140bbf
Create Date: 2021-05-13 20:34:57.092215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ef8552e5d5'
down_revision = '686380140bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_uuid'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###
