dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - python -m pip install -r requirements/dev.txt

before_script:
  - cd app
  - flask db upgrade
  - cd ..
script:
  - pytest --cov=app --cov-config=app/.coveragerc
after_success:
  - coveralls