dist: xenial
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9

# install dependencies
before_install:
  - python -m pip install --upgrade pip
install:
  - python -m pip install -r requirements/dev.txt

before_script:
  - cd module
  - flask db upgrade
  - cd ..
script:
  - pytest --cov=module --cov-config=module/.coveragerc --cov-report term-missing
after_success:
  - coveralls